apiVersion: apps/v1
kind: Deployment
metadata:
  name: carrsh-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carrsh-web-pod
  template:
    metadata:
      labels:
        app: carrsh-web-pod
    spec:
      containers:
      - name: carrsh-web
        image: philipsung/carrsh-web-image:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
