apiVersion: v1
kind: Service
metadata:
  name: carrsh-back-service
spec:
  selector:
    app: carrsh-back-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 32580
  type: NodePort
