apiVersion: apps/v1
kind: Deployment
metadata:
  name: carrsh-back-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carrsh-back-pod
  template:
    metadata:
      labels:
        app: carrsh-back-pod
    spec:
      containers:
      - name: carrsh-back
        image: philipsung/carrsh-image:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: carrsh-back-env
