apiVersion: apps/v1
kind: Deployment
metadata:
  name: pserver-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pserver-web-pod
  template:
    metadata:
      labels:
        app: pserver-web-pod
    spec:
      containers:
      - name: pserver-web
        image: philipsung/pserver-web-image:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
